version: '3'

networks: 
  test:
services: 
  nginx:
    image: nginx
    container_name: nginx
    networks:
      - test
    volumes:
      - $PWD/nginx/:/etc/nginx/conf.d/
      - $PWD/www/:/var/www/
    ports:
      - '8888:80'
    depends_on:
      - php
  php:
    build:
      context: ./php/
      dockerfile: Dockerfile
    container_name: php
    networks:
      - test
    volumes:
      - $PWD/www/:/var/www/
      - $PWD/php/php.ini-development:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  composer:
    image: composer
    container_name: php-composer
    volumes:
      - $PWD/www/:/var/www/
    tty: true
    command: ['/bin/bash']
    networks:
      - test
    working_dir: /var/www/html/my-project
    depends_on:
      - php
  mysql:
    image: mysql
    container_name: mysql
    ports: 
      - '3306:3306'
    command:
      - "--default-authentication-plugin=mysql_native_password"
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - $PWD/mysql/:/var/lib/mysql/
    networks:
      - test